test fixed compose4

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,72 +8,57 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+    - uses: actions/checkout@v2
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+    - name: Set up Docker Compose
+      run: |
+        sudo apt-get update
+        sudo apt-get install docker-compose
 
-      - name: Build docker image
-        run: |
-          docker buildx build . -t $REPO_NAME/$IMAGE_NAME --push
+    - name: Build and run Docker Compose
+      run: |
+        docker-compose up --build -d
+        sleep 30
 
-      - name: Set up Docker Compose
-        run: |
-          docker-compose -v
+    - name: "Check files existence"
+      uses: andstor/file-existence-action@v2
+      with:
+        files: "postman/collection.json,postman/environment.json"
+        fail: true
 
-      - name: Start services with Docker Compose
-        run: |
-          docker-compose up -d
+    - name: Run API Tests
+      id: run-newman
+      uses: anthonyvscode/newman-action@master
+      with:
+        collection: postman/collection.json
+        environment: postman/environment.json
+        reporters: cli
+        bail: true
 
-      - name: Wait for MongoDB to be ready
-        run: |
-          for i in {1..30}; do
-            nc -z localhost 27017 && break || sleep 3;
-          done
+    - name: Check if we failed
+      id: fail-check
+      shell: bash
+      env:
+        JSON_DOC: ${{ steps.run-newman.outputs.summary }}
+      run: |
+        printf '%s\n' "$JSON_DOC" > summary.json
+        cat summary.json
+        if grep -q Collection summary.json; then
+          echo "failed=false" >> $GITHUB_OUTPUT;
+        else
+          echo "failed=true" >> $GITHUB_OUTPUT;
+        fi
 
-      - name: Wait for application to be ready
-        run: |
-          for i in {1..30}; do
-            nc -z localhost 8080 && break || sleep 3;
-          done
+    - name: Fail if tests failed
+      if: ${{ steps.fail-check.outputs.failed == 'true' }}
+      run: exit 1
 
-      - name: Run API Tests
-        id: run-newman
-        uses: anthonyvscode/newman-action@master
-        with:
-          collection: postman/collection.json
-          environment: postman/environment.json
-          reporters: cli
-          bail: true
+    - name: Login to Container Registry
+      uses: docker/login-action@v1
+      with:
+        username: ${{ secrets.REGISTRY_USERNAME }}
+        password: ${{ secrets.REGISTRY_PASSWORD }}
 
-      - name: Check if we failed
-        id: fail-check
-        shell: bash
-        env:
-          JSON_DOC: ${{ steps.run-newman.outputs.summary }}
-        run: |
-          printf '%s\n' "$JSON_DOC" > summary.json
-          cat summary.json
-          if grep -q Collection summary.json; then
-            echo "failed=false" >> $GITHUB_OUTPUT;
-          else
-            echo "failed=true" >> $GITHUB_OUTPUT;
-          fi
-
-      - name: Fail if tests failed
-        if: ${{ steps.fail-check.outputs.failed == 'true' }}
-        run: exit 1
-
-      - name: Clean up Docker containers
-        run: |
-          docker-compose down
-
-      - name: Login to Container Registry
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.REGISTRY_USERNAME }}
-          password: ${{ secrets.REGISTRY_PASSWORD }}
-
-      - name: Push image to Docker Hub
-        run: |
-          docker push $REPO_NAME/$IMAGE_NAME
+    - name: Push image to Docker Hub
+      run: | 
+        docker push $REPO_NAME/$IMAGE_NAME
