test fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,10 @@
-name: Build Test and Push
-on: [push]
+name: Build, Test, and Push
+
+on:
+  push:
+    branches:
+      - main
+
 env:
   IMAGE_NAME: student_service
   REPO_NAME: jkasikci/student_service
@@ -8,61 +13,64 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Build Docker image
-      run: |
-        docker build . -t $REPO_NAME/$IMAGE_NAME
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v1
 
-    - name: Run Docker container
-      run: |
-        docker run -d --name student_service -p 8080:8080 --link mongodb:mongodb \
-          $REPO_NAME/$IMAGE_NAME:latest
-        sleep 30
+      - name: Build Docker image
+        run: |
+          docker build . -t $REPO_NAME/$IMAGE_NAME
 
-    - name: View Docker container logs
-      run: |
-        docker logs student_service
+      - name: Run MongoDB container
+        run: |
+          docker network create my_network
+          docker run -d --name mongodb --network my_network -p 27017:27017 mongo:latest
 
-    - name: "Check files existence"
-      uses: andstor/file-existence-action@v2
-      with:
-        files: "postman/collection.json,postman/environment.json"
-        fail: true
+      - name: Run student service container
+        run: |
+          docker run -d --name student_service --network my_network -p 8080:8080 $REPO_NAME/$IMAGE_NAME:latest
 
-    - name: Run API Tests
-      id: run-newman
-      uses: anthonyvscode/newman-action@master
-      with:
-        collection: postman/collection.json
-        environment: postman/environment.json
-        reporters: cli
-        bail: true
+      - name: Check files existence
+        uses: andstor/file-existence-action@v2
+        with:
+          files: "postman/collection.json,postman/environment.json"
+          fail: true
 
-    - name: Check if we failed
-      id: fail-check
-      shell: bash
-      env:
-        JSON_DOC: ${{ steps.run-newman.outputs.summary }}
-      run: |
-        printf '%s\n' "$JSON_DOC" > summary.json
-        cat summary.json
-        if grep -q Collection summary.json; then
-          echo "failed=false" >> $GITHUB_OUTPUT;
-        else
-          echo "failed=true" >> $GITHUB_OUTPUT;
-        fi
+      - name: Run API tests
+        id: run-newman
+        uses: anthonyvscode/newman-action@master
+        with:
+          collection: postman/collection.json
+          environment: postman/environment.json
+          reporters: cli
+          bail: true
 
-    - name: Fail if tests failed
-      if: ${{ steps.fail-check.outputs.failed == 'true' }}
-      run: exit 1
+      - name: Check if we failed
+        id: fail-check
+        shell: bash
+        env:
+          JSON_DOC: ${{ steps.run-newman.outputs.summary }}
+        run: |
+          printf '%s\n' "$JSON_DOC" > summary.json
+          cat summary.json
+          if grep -q Collection summary.json; then
+            echo "failed=false" >> $GITHUB_OUTPUT;
+          else
+            echo "failed=true" >> $GITHUB_OUTPUT;
+          fi
 
-    - name: Login to Container Registry
-      uses: docker/login-action@v1
-      with:
-        username: ${{ secrets.REGISTRY_USERNAME }}
-        password: ${{ secrets.REGISTRY_PASSWORD }}
+      - name: Fail if empty
+        if: ${{ steps.fail-check.outputs.failed == 'true' }}
+        run: exit 1
 
-    - name: Push image to Docker Hub
-      run: | 
-        docker push $REPO_NAME/$IMAGE_NAME
+      - name: Login to Container Registry
+        uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.REGISTRY_USERNAME }}
+          password: ${{ secrets.REGISTRY_PASSWORD }}
+
+      - name: Push image to Docker Hub
+        run: |
+          docker push $REPO_NAME/$IMAGE_NAME
